# version: '3'
# services:
#   nextjs: 
#     build: ./
#   nginx:
#     image: nginx:alpine
#     restart: unless-stopped
#     volumes:
#         - ./data/nginx:/etc/nginx/conf.d
#         - ./data/certbot/conf:/etc/letsencrypt
#         - ./data/certbot/www:/var/www/certbot
#     ports:
#         - 80:80
#         - 443:443
#     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    # version: '3'
services:
  nextjs: 
    build: ./
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: nhd.ars@gmail.com
        STAGING: 0
        DHPARAM_SIZE: 2048
        RSA_KEY_SIZE: 2048
        RENEWAL_INTERVAL: 8d
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
volumes:
    letsencrypt: